name: Kernel Build for Realme C20A

on:
  workflow_dispatch:  # Manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3
      
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y bc build-essential gcc-aarch64-linux-gnu \
        gcc-arm-linux-gnueabi libssl-dev ccache make flex bison \
        libncurses-dev git wget curl lzop

    - name: Set Up Environment
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        
    - name: Configure Kernel
      run: |
        make O=out realme_defconfig
    
    - name: Compile Kernel
      run: |
        make -j$(nproc) O=out
    
    - name: Upload Kernel Image
      uses: actions/upload-artifact@v3
      with:
        name: Kernel-Image
        path: out/arch/arm64/boot/Image
        
